apiVersion: apps/v1
kind: Deployment
metadata:
  name: ci-testing-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ci-testing
  template:
    metadata:
      labels:
        app: ci-testing
    spec:
      containers:
      - name: app
        image: ci-testing-app
        ports:
        - containerPort: 8080
